/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: LowPolyBoy (https://sketchfab.com/lowPolyBoy)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/free-isometric-cafe-a945f20219c44e94a77cf76929368470
title: (FREE) Isometric Cafe
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export default function Bakery(props) {
  const { nodes, materials } = useGLTF('/models/free_isometric_cafe.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.06, 0]}>
            <group position={[0.74, 0.95, -0.48]}>
              <group position={[-0.05, 0, 0.05]} rotation={[0, -0.39, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_11.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.05, 0, -0.05]} rotation={[0, -0.39, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0.06, 0, 0.05]} rotation={[0, -0.39, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_15.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0.05, 0, -0.05]} rotation={[0, -0.39, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_17.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                position={[-0.05, 0.04, 0.05]}
                rotation={[0.17, -0.97, -0.02]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_19.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[-0.05, 0.04, -0.05]}
                rotation={[-0.23, -0.35, -0.2]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_21.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[0.06, 0.04, 0.05]}
                rotation={[0.15, -0.29, 0.04]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_23.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[0.05, 0.04, -0.05]}
                rotation={[-0.17, 0.44, 0.04]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_25.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_9.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[-0.58, 0.75, -0.86]}>
              <group position={[0, -0.01, -0.06]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_29.geometry}
                  material={materials.Wood}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_31.geometry}
                  material={materials.Shop}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials.Emmision}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_27.geometry}
                material={materials.Shop}
              />
            </group>
            <group position={[0.02, 1.51, -0.84]} rotation={[0, 0.1, 0]}>
              <group position={[0.24, 0, 0.11]} rotation={[0, -0.21, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_35.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0.24, 0, 0.02]} rotation={[0, -0.25, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_37.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0.12, 0, 0.1]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_39.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0.12, 0, 0.01]} rotation={[0, -0.1, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_41.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.01, 0, 0.09]} rotation={[0, -0.22, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_43.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_33.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.74, 0.42, 0.38]} rotation={[0, 1.52, 0]}>
              <group position={[-0.2, 0.38, 0.04]} rotation={[0, -1.52, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_47.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0.01, 0.38, 0]} rotation={[0, 0.05, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_49.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.02, 0.19, 0]} rotation={[0, 0.11, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_51.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.13, 0.19, 0.01]} rotation={[0, -0.06, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_53.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.23, 0.19, 0.01]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_55.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.11, 0, 0.01]} rotation={[0, 0.22, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_57.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.23, 0, 0.01]} rotation={[0, -0.08, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_59.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.08, 0.36, 0]} rotation={[0, -1.52, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_61.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.19, 0.35, -0.05]} rotation={[0, -0.2, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_63.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0, -0.24, 0]} rotation={[0, -1.24, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_65.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[-0.12, -0.24, 0.06]}
                rotation={[-Math.PI, 0.23, -Math.PI]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_67.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[-0.19, -0.24, -0.03]}
                rotation={[-Math.PI, -0.19, -Math.PI]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_69.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_45.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[-0.86, 0.55, 0.85]}>
              <group
                position={[0.27, -0.25, 0.04]}
                rotation={[0, Math.PI / 2, 0]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_73.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.02, -0.2, -1.16]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_75.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[0.14, -0.2, -0.69]}
                rotation={[0, -Math.PI / 2, 0]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_77.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[0.14, -0.2, -0.29]}
                rotation={[0, -Math.PI / 2, 0]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_79.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[0.49, -0.2, 0.02]}
                rotation={[0, -Math.PI / 2, 0]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_81.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[0.02, 0.03, -0.58]}
                rotation={[-Math.PI, 0.64, -Math.PI]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_83.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.05, 0.03, -0.36]} rotation={[0, -0.86, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_85.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[-0.04, 0.03, -0.7]}
                rotation={[0, -0.39, 0]}
                scale={[1.72, 1, 1.72]}
              >
                <group
                  position={[0, 0.03, 0]}
                  rotation={[-Math.PI, 0.59, -Math.PI]}
                  scale={[0.75, 1.29, 0.75]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_89.geometry}
                    material={materials.tbjr_material}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_87.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[0, 0.03, -0.22]}
                rotation={[0, -0.39, 0]}
                scale={[1.72, 1, 1.72]}
              >
                <group
                  position={[-0.01, 0.02, -0.02]}
                  rotation={[0.27, 0.38, -0.08]}
                  scale={[0.58, 0.98, 0.61]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_93.geometry}
                    material={materials.tbjr_material}
                  />
                </group>
                <group
                  position={[0.01, 0.02, 0.02]}
                  rotation={[2.87, -0.38, 3.06]}
                  scale={[0.58, 0.98, 0.61]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_95.geometry}
                    material={materials.tbjr_material}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_91.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_71.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group
              position={[0.8, 0.64, -0.03]}
              rotation={[0, -Math.PI / 2, 0]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_97.geometry}
                material={materials.gradient_glossy}
              />
            </group>
            <group position={[0.59, 0.65, -0.61]} rotation={[0, -0.34, 0.17]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_99.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.49, 1.17, -0.79]}>
              <group position={[0, 0.06, 0.04]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_103.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0.04, 0.06, -0.02]} rotation={[0, -0.96, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_105.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.04, 0.06, -0.02]} rotation={[0, 0.91, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_107.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0.04, 0.09, 0.02]} rotation={[0, 1.01, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_109.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0.01, 0.09, -0.04]} rotation={[0, 0.06, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_111.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[-0.04, 0.09, 0.02]}
                rotation={[-Math.PI, 1.21, -Math.PI]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_113.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0.02, 0.13, 0]} rotation={[0, 1.32, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_115.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.02, 0.13, -0.01]} rotation={[0, 1.32, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_117.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_101.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[-0.37, 1.54, -0.76]}>
              <group position={[-0.38, 0.04, 0]} rotation={[0, 0.29, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_121.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.28, 0.03, 0.02]} rotation={[0, -0.03, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_123.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.01, 0.2, 0]} rotation={[0, -0.24, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_125.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.11, 0.2, 0]} rotation={[0, 0.13, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_127.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.01, 0.2, -0.07]} rotation={[0, 0.11, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_129.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.1, 0.2, -0.07]} rotation={[0, -0.18, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_131.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.1, 0, 0]} rotation={[0, -0.32, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_133.geometry}
                  material={materials.gradient_glossy}
                />
              </group>
              <group position={[-0.19, 0, 0]} rotation={[0, 0.3, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_135.geometry}
                  material={materials.gradient_glossy}
                />
              </group>
              <group position={[-0.31, 0.17, -0.01]} rotation={[0, -0.52, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_137.geometry}
                  material={materials.gradient_glossy}
                />
              </group>
              <group position={[-0.4, 0.17, -0.01]} rotation={[0, 0.3, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_139.geometry}
                  material={materials.gradient_glossy}
                />
              </group>
              <group position={[-0.21, 0.17, -0.01]} rotation={[0, -0.05, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_141.geometry}
                  material={materials.gradient_glossy}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_119.geometry}
                material={materials.gradient_glossy}
              />
            </group>
            <group position={[-0.29, 0.17, -0.53]} rotation={[0, 1.19, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_143.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[-0.11, 1.5, -0.81]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_145.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.76, 0.17, 0.86]} rotation={[0, 1.19, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_147.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group
              position={[0.76, 1.17, 0.43]}
              rotation={[Math.PI, -1.15, Math.PI]}
            >
              <group position={[-0.01, 0.18, 0.01]} rotation={[0, 0.39, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_151.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0.08, 0.18, -0.03]} rotation={[0, 0.52, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_153.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0.21, 0.32, -0.11]} rotation={[0, 0.39, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_155.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0.31, 0.32, -0.15]} rotation={[0, 0.52, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_157.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0.18, 0.15, -0.08]} rotation={[0, 0.59, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_159.geometry}
                  material={materials.gradient_glossy}
                />
              </group>
              <group position={[0.28, 0.15, -0.13]} rotation={[0, 0.05, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_161.geometry}
                  material={materials.gradient_glossy}
                />
              </group>
              <group position={[0.28, 0, -0.13]} rotation={[0, 0.05, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_163.geometry}
                  material={materials.gradient_glossy}
                />
              </group>
              <group position={[0.19, 0, -0.08]} rotation={[0, 0.05, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_165.geometry}
                  material={materials.gradient_glossy}
                />
              </group>
              <group position={[0.09, 0, -0.04]} rotation={[0, 0.77, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_167.geometry}
                  material={materials.gradient_glossy}
                />
              </group>
              <group position={[-0.02, 0.27, 0.04]} rotation={[0, 0.59, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_169.geometry}
                  material={materials.gradient_glossy}
                />
              </group>
              <group position={[0.02, 0.27, 0.02]} rotation={[0, 0.05, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_171.geometry}
                  material={materials.gradient_glossy}
                />
              </group>
              <group position={[0.08, 0.27, -0.01]} rotation={[0, 0.59, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_173.geometry}
                  material={materials.gradient_glossy}
                />
              </group>
              <group position={[0.12, 0.27, -0.03]} rotation={[0, 0.05, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_175.geometry}
                  material={materials.gradient_glossy}
                />
              </group>
              <group position={[-0.03, 0.29, -0.04]} rotation={[0, 0.47, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_177.geometry}
                  material={materials.gradient_glossy}
                />
              </group>
              <group position={[0.06, 0.29, -0.08]} rotation={[0, 0.16, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_179.geometry}
                  material={materials.gradient_glossy}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_149.geometry}
                material={materials.gradient_glossy}
              />
            </group>
            <group position={[-0.11, 0.66, -0.7]}>
              <group position={[0, 0.1, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_183.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_181.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.1, 0.66, -0.7]}>
              <group position={[-0.04, 0.11, 0]} rotation={[0.01, 0.57, -0.1]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_187.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[0.02, 0.11, 0.06]}
                rotation={[0.02, 1.15, -0.12]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_189.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_185.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.31, 0.66, -0.7]}>
              <group
                position={[-0.04, 0.1, 0.03]}
                rotation={[-0.38, 0.57, 0.79]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_193.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[-0.02, 0.1, -0.05]}
                rotation={[0.23, 0.61, -0.09]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_195.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[0.06, 0.1, 0.01]}
                rotation={[-0.31, 0.65, 0.45]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_197.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[0.01, 0.1, 0.05]}
                rotation={[Math.PI, 1.4, -2.42]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_199.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_191.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group
              position={[0.31, 0.76, -0.7]}
              rotation={[-Math.PI, 1.4, -Math.PI]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_201.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group
              position={[0.01, 0.76, 0.11]}
              rotation={[Math.PI, -1.46, Math.PI]}
            >
              <group
                position={[-0.02, 0.11, -0.02]}
                rotation={[0.01, 0.57, -0.1]}
                scale={0.86}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_205.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[0.03, 0.11, 0.04]}
                rotation={[0.02, 1.15, -0.12]}
                scale={0.86}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_207.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_203.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[-0.05, 1.14, -0.79]}>
              <group position={[0.05, 0.05, -0.04]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_212.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0.05, 0.05, 0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_214.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.05, 0.05, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_216.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[-0.07, 0.07, 0.04]}
                rotation={[-0.14, 0.68, -0.21]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_218.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[0.01, 0.08, 0.04]}
                rotation={[0.13, 0.36, -0.11]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_220.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[0, 0.08, -0.03]}
                rotation={[-0.01, -0.24, -0.01]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_222.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0, 0.05, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_224.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_210.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_209.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.2, 1.14, -0.79]}>
              <group position={[0, 0.05, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_229.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0, 0.06, 0.01]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_231.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[-0.06, 0.09, -0.01]}
                rotation={[2.1, -0.7, 2.24]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_233.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[0.05, 0.09, -0.01]}
                rotation={[2.05, 0.73, -2.3]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_235.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_227.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_226.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.73, 1.18, -0.79]}>
              <group position={[0.05, 0, -0.04]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_239.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0.05, 0, 0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_241.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.05, 0, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_243.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[-0.07, 0.03, 0.04]}
                rotation={[-0.14, 0.68, -0.21]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_245.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[0.01, 0.04, 0.04]}
                rotation={[0.13, 0.36, -0.11]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_247.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[0, 0.03, -0.03]}
                rotation={[-0.01, -0.24, -0.01]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_249.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[0, -0.05, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_252.geometry}
                  material={materials.material_0}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_251.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_237.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.73, 1.43, -0.79]}>
              <group position={[0.06, 0.05, 0]} rotation={[0, -0.06, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_257.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.01, 0.05, 0]} rotation={[0, 0.06, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_259.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.29, 0.05, 0]} rotation={[0, -0.04, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_261.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[-0.12, 0.05, -0.03]}
                rotation={[-Math.PI, 1.55, -Math.PI]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_263.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[-0.12, 0.05, 0.03]}
                rotation={[0, Math.PI / 2, 0]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_265.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.22, 0.05, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_267.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_255.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_254.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.08, 0.6, 0.24]}>
              <group position={[-0.24, 0.03, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_272.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.17, 0.03, -0.03]} rotation={[0, -0.81, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_274.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.24, 0.03, 0.03]} rotation={[0, -0.95, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_276.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.17, 0.03, 0.03]} rotation={[0, 0.63, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_278.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.1, 0.03, -0.03]} rotation={[0, -0.81, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_280.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.1, 0.03, 0.03]} rotation={[0, 0.63, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_282.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_270.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_269.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.08, 0.6, 0.41]}>
              <group position={[-0.24, 0.03, 0.03]} rotation={[0, -0.77, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_287.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.17, 0.03, -0.03]} rotation={[0, -0.46, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_289.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.17, 0.03, 0.03]} rotation={[0, 0.4, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_291.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.24, 0.03, -0.03]} rotation={[0, 0.33, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_293.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.11, 0.03, -0.03]} rotation={[0, 0.46, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_295.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.11, 0.03, 0.03]} rotation={[0, -0.08, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_297.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_285.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_284.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.08, 0.6, 0.06]}>
              <group position={[-0.22, 0.03, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_302.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.16, 0.03, 0.02]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_304.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[-0.23, 0.05, 0.03]}
                rotation={[0.87, -0.74, 0.47]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_306.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.1, 0.03, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_308.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_300.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_299.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.08, 0.38, 0.41]}>
              <group position={[-0.24, 0.03, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_313.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.17, 0.03, -0.03]} rotation={[0, -0.81, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_315.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.24, 0.03, 0.03]} rotation={[0, -0.95, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_317.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.17, 0.03, 0.03]} rotation={[0, 0.63, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_319.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.1, 0.03, -0.03]} rotation={[0, -0.81, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_321.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.1, 0.03, 0.03]} rotation={[0, 0.63, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_323.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_311.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_310.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.08, 0.38, 0.24]}>
              <group position={[-0.23, 0.02, 0.04]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_328.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[-0.19, 0.02, -0.02]}
                rotation={[-Math.PI, 1.23, -Math.PI]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_330.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.15, 0.02, 0.04]} rotation={[0, 0.69, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_332.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.11, 0.02, -0.02]} rotation={[0, 0.75, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_334.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_326.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_325.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.08, 0.38, 0.06]}>
              <group position={[-0.24, 0.03, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_339.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.24, 0.03, 0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_341.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.17, 0.03, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_343.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.17, 0.03, 0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_345.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.1, 0.03, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_347.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.1, 0.03, 0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_349.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_337.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_336.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.08, 0.17, 0.24]}>
              <group position={[-0.24, 0.03, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_354.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.24, 0.03, 0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_356.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.17, 0.03, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_358.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.17, 0.03, 0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_360.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.1, 0.03, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_362.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.1, 0.03, 0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_364.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_352.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_351.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.08, 0.17, 0.41]}>
              <group position={[-0.22, 0.03, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_369.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.16, 0.03, 0.02]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_371.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group
                position={[-0.23, 0.05, 0.03]}
                rotation={[0.87, -0.74, 0.47]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_373.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.1, 0.03, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_375.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_367.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_366.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.08, 0.17, 0.06]}>
              <group position={[-0.24, 0.03, -0.03]} rotation={[0, 0.33, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_380.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.24, 0.03, 0.03]} rotation={[0, -0.77, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_382.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.17, 0.03, -0.03]} rotation={[0, -0.46, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_384.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.17, 0.03, 0.03]} rotation={[0, 0.4, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_386.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.11, 0.03, -0.03]} rotation={[0, 0.46, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_388.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.11, 0.03, 0.03]} rotation={[0, -0.08, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_390.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_378.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_377.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <group position={[0.85, 1.89, -0.89]}>
              <group position={[0, -0.23, 0.92]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_394.geometry}
                  material={materials.Shop}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_395.geometry}
                  material={materials.Emmision}
                />
              </group>
              <group position={[0, -0.17, 1.08]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_397.geometry}
                  material={materials.Shop}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_398.geometry}
                  material={materials.Emmision}
                />
              </group>
              <group position={[0, -0.1, 1.24]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_400.geometry}
                  material={materials.Shop}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_401.geometry}
                  material={materials.Emmision}
                />
              </group>
              <group position={[0, -0.18, 1.43]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_403.geometry}
                  material={materials.Shop}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_404.geometry}
                  material={materials.Emmision}
                />
              </group>
              <group position={[0, -0.2, 1.63]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_406.geometry}
                  material={materials.Shop}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_407.geometry}
                  material={materials.Emmision}
                />
              </group>
              <group position={[0, -0.12, 1.8]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_409.geometry}
                  material={materials.Shop}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_410.geometry}
                  material={materials.Emmision}
                />
              </group>
              <group position={[0, -0.15, 0.74]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_412.geometry}
                  material={materials.Shop}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_413.geometry}
                  material={materials.Emmision}
                />
              </group>
              <group position={[0, -0.12, 0.56]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_415.geometry}
                  material={materials.Shop}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_416.geometry}
                  material={materials.Emmision}
                />
              </group>
              <group position={[0, -0.21, 0.39]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_418.geometry}
                  material={materials.Shop}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_419.geometry}
                  material={materials.Emmision}
                />
              </group>
              <group position={[0, -0.17, 0.15]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_421.geometry}
                  material={materials.Shop}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_422.geometry}
                  material={materials.Emmision}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_392.geometry}
                material={materials.Shop}
              />
            </group>
            <group position={[0.01, 0.76, 0.2]} rotation={[0, Math.PI / 2, 0]}>
              <group position={[-0.22, 0.03, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_427.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.22, 0.03, 0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_429.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.16, 0.03, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_431.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.16, 0.03, 0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_433.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.09, 0.03, -0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_435.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <group position={[-0.09, 0.03, 0.03]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_437.geometry}
                  material={materials.tbjr_material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_425.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_424.geometry}
                material={materials.tbjr_material}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials.wall2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.Menu}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials.Shop}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials.Emmision}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/free_isometric_cafe.glb')
