/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: its_sagar_bro (https://sketchfab.com/its_sagar_bro)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-house-796232a307d24b6881f4f42476058701
title: Low poly house
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export default function House(props: any) {
  const { nodes, materials } = useGLTF('/models/low_poly_house.glb') as any
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.House_Complete001_House_Complete_0.geometry}
            material={materials.House_Complete}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/low_poly_house.glb')
